import type { Metadata } from "next";
import { Timmana, Public_Sans } from "next/font/google";
import "./globals.css";

const timmana = Timmana({
  variable: "--font-timmana",
  subsets: ["latin"],
  weight: "400",
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${timmana.variable} ${publicSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
